"""Promote one successful candidate run by digest; never build an image.

Invoked only by the manually dispatched promotion workflow. The release tag must
already exist at the candidate's exact commit. No moving channel tags are created.
"""

import argparse
import json
import os
import subprocess
from pathlib import Path

from release_artifacts import REPOSITORY, run, verify


def api(path: str) -> dict:
    return json.loads(run("gh", "api", f"repos/{REPOSITORY}/{path}"))


def eligible(candidate: dict, manifest: dict) -> None:
    if (
        candidate["path"] != ".github/workflows/release-candidate.yml"
        or candidate["event"] != "workflow_dispatch"
        or candidate["status"] != "completed"
        or candidate["conclusion"] != "success"
        or candidate["run_attempt"] != 1
        or candidate["head_sha"] != manifest["revision"]
        or candidate["repository"]["full_name"] != REPOSITORY
    ):
        raise ValueError(
            "candidate must be a successful release-candidate run at this exact commit"
        )


def digest(reference: str) -> str:
    return json.loads(
        run(
            "docker",
            "buildx",
            "imagetools",
            "inspect",
            reference,
            "--format",
            "{{json .Manifest.Digest}}",
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("candidate_run", type=int)
    parser.add_argument("directory", type=Path)
    args = parser.parse_args()
    manifest = verify(args.directory)
    candidate = api(f"actions/runs/{args.candidate_run}")
    eligible(candidate, manifest)
    version = manifest["version"]
    # Fetch the existing tag only. This command never creates or moves a Git tag.
    subprocess.run(["git", "fetch", "origin", f"refs/tags/{version}"], check=True)
    if run("git", "rev-parse", "FETCH_HEAD^{commit}") != manifest["revision"]:
        raise ValueError("release tag does not point to the gated candidate commit")
    if run("git", "rev-parse", "HEAD") != manifest["revision"]:
        raise ValueError("promotion workflow must run at the candidate commit (select its tag)")
    releases = json.loads(run("gh", "api", "--paginate", "--slurp", f"repos/{REPOSITORY}/releases"))
    if any(release["tag_name"] == version for page in releases for release in page):
        raise ValueError("release already exists; versioned releases are never overwritten")
    # Probe all targets before writing anything. A prior partial promotion may
    # be retried only if each already-created version tag has this exact digest.
    for component in ("api", "web"):
        reference = manifest["images"][component]
        image, expected = reference.split("@")
        if digest(reference) != expected:
            raise ValueError("candidate digest changed")
        result = subprocess.run(
            [
                "docker",
                "buildx",
                "imagetools",
                "inspect",
                f"{image}:{version}",
                "--format",
                "{{json .Manifest.Digest}}",
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            if json.loads(result.stdout) != expected:
                raise ValueError(f"refusing to overwrite {image}:{version}")
        elif (
            "not found" not in result.stderr.lower()
            and "manifest unknown" not in result.stderr.lower()
        ):
            raise ValueError(f"cannot establish whether {image}:{version} exists: {result.stderr}")
    for component in ("api", "web"):
        reference = manifest["images"][component]
        image, expected = reference.split("@")
        subprocess.run(
            [
                "docker",
                "buildx",
                "imagetools",
                "create",
                "--prefer-index=false",
                "--tag",
                f"{image}:{version}",
                reference,
            ],
            check=True,
        )
        if digest(f"{image}:{version}") != expected:
            raise ValueError("promotion changed the tested image index")
    # Draft only. The owner adds the release notes and publishes separately after
    # the deployment/client gate. The download assets are byte-for-byte the gated bundle.
    notes = Path(os.environ["RUNNER_TEMP"]) / "release-notes.md"
    notes.write_text(
        "**GPT-6 (OpenAI) — release artifact record, generated by the release workflow.**\n\n"
        f"Artifacts for `{version}`, source `{manifest['revision']}`.\n\n"
        f"Candidate gate: https://github.com/{REPOSITORY}/actions/runs/{args.candidate_run}\n\n"
        "Both Linux architectures passed the candidate CI gate. `release.json` records "
        "the exact image digests and asset checksums. No images were rebuilt during promotion.\n\n"
        "Maintainer: add the release changes, data/migration consequences and observed "
        "deployment/client gate results before publishing this draft.\n\n"
        "— **GPT-6 (OpenAI)**, via Codex release tooling\n"
    )
    subprocess.run(
        [
            "gh",
            "release",
            "create",
            version,
            "--repo",
            REPOSITORY,
            "--verify-tag",
            "--draft",
            *(["--prerelease"] if "-alpha" in version else []),
            "--title",
            version,
            "--notes-file",
            str(notes),
            *(str(path) for path in sorted(args.directory.iterdir())),
        ],
        check=True,
    )


if __name__ == "__main__":
    main()
