"""retailer ratings

Revision ID: e720578b82de
Revises: 6cbd8315df95
Create Date: 2026-08-06 01:43:10.386992

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e720578b82de"
down_revision: str | None = "6cbd8315df95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # (autogenerate's spurious enum CHECK drops removed by hand — known false positive)
    op.add_column("retailers", sa.Column("rating", sa.Integer(), nullable=True))
    op.add_column(
        "retailers",
        sa.Column(
            "packing_quality",
            sa.Enum(
                "excellent",
                "good",
                "average",
                "below_average",
                "poor",
                name="packing_quality",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "retailers",
        sa.Column(
            "shipping_speed",
            sa.Enum(
                "very_fast",
                "fast",
                "average",
                "slow",
                "very_slow",
                name="shipping_speed",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "retailers",
        sa.Column(
            "would_order_again",
            sa.Enum(
                "yes",
                "maybe",
                "no",
                name="would_order_again",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        op.f("ck_retailers_rating_range"), "retailers", "rating BETWEEN 1 AND 5"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_retailers_rating_range"), "retailers", type_="check")
    op.drop_column("retailers", "would_order_again")
    op.drop_column("retailers", "shipping_speed")
    op.drop_column("retailers", "packing_quality")
    op.drop_column("retailers", "rating")
