"""orders shipped_at (#95)

One nullable timestamptz. Purely a timeline record plus the in_transit kit
advance — no stock semantics, no backfill (an order received without ever being
marked shipped keeps a null shipped_at; deriving one would fabricate a fact).

The autogenerated text-enum CHECK drop/create noise was hand-removed, as on
every migration since the enums became text + CHECK (rule 5).

Revision ID: bcdb375e32d0
Revises: 8352bee9229f
Create Date: 2026-08-20 23:58:46.705100

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bcdb375e32d0"
down_revision: str | None = "8352bee9229f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("orders", sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column("orders", "shipped_at")
