"""initial schema

Revision ID: 71ddc06de024
Revises:
Create Date: 2026-08-06 00:27:20.156332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "71ddc06de024"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consumables",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "quantity_on_hand >= 0", name=op.f("ck_consumables_quantity_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consumables")),
    )
    op.create_index(op.f("ix_consumables_name"), "consumables", ["name"], unique=False)
    op.create_table(
        "retailers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retailers")),
    )
    op.create_index(op.f("ix_retailers_name"), "retailers", ["name"], unique=False)
    op.create_table(
        "tools",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("unit_cost_reference", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("condition_notes", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity_on_hand >= 0", name=op.f("ck_tools_quantity_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tools")),
    )
    op.create_index(op.f("ix_tools_name"), "tools", ["name"], unique=False)
    op.create_table(
        "upgrades",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity_on_hand >= 0", name=op.f("ck_upgrades_quantity_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upgrades")),
    )
    op.create_index(op.f("ix_upgrades_name"), "upgrades", ["name"], unique=False)
    op.create_table(
        "orders",
        sa.Column("retailer_id", sa.Uuid(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("delivery_service", sa.String(), nullable=True),
        sa.Column("tracking_number", sa.String(), nullable=True),
        sa.Column("tracking_url", sa.String(), nullable=True),
        sa.Column("shipping_cost_minor", sa.Integer(), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["retailer_id"], ["retailers.id"], name=op.f("fk_orders_retailer_id_retailers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "kit",
                "tool",
                "consumable",
                "upgrade",
                name="item_type",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("catalog_ref_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_minor", sa.Integer(), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("converted_price_aud_minor", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price_minor >= 0", name=op.f("ck_order_items_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "kits",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("grade", sa.String(), nullable=False),
        sa.Column("scale", sa.String(), nullable=True),
        sa.Column("kit_number", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "backlog",
                "pre_ordered",
                "ordered",
                "in_transit",
                "in_hand",
                "building",
                "complete",
                name="kit_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("build_notes", sa.Text(), nullable=True),
        sa.Column("order_item_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_kits_rating_range")),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
            name=op.f("fk_kits_order_item_id_order_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kits")),
    )
    op.create_index(op.f("ix_kits_status"), "kits", ["status"], unique=False)
    op.create_table(
        "kit_photos",
        sa.Column("kit_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kit_id"], ["kits.id"], name=op.f("fk_kit_photos_kit_id_kits"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kit_photos")),
    )
    op.create_index(op.f("ix_kit_photos_kit_id"), "kit_photos", ["kit_id"], unique=False)
    op.create_table(
        "upgrade_applications",
        sa.Column("upgrade_id", sa.Uuid(), nullable=False),
        sa.Column("kit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_used", sa.Integer(), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "quantity_used > 0", name=op.f("ck_upgrade_applications_quantity_used_positive")
        ),
        sa.ForeignKeyConstraint(
            ["kit_id"],
            ["kits.id"],
            name=op.f("fk_upgrade_applications_kit_id_kits"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["upgrade_id"],
            ["upgrades.id"],
            name=op.f("fk_upgrade_applications_upgrade_id_upgrades"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upgrade_applications")),
    )
    op.create_index(
        op.f("ix_upgrade_applications_kit_id"), "upgrade_applications", ["kit_id"], unique=False
    )
    op.create_index(
        op.f("ix_upgrade_applications_upgrade_id"),
        "upgrade_applications",
        ["upgrade_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_upgrade_applications_upgrade_id"), table_name="upgrade_applications")
    op.drop_index(op.f("ix_upgrade_applications_kit_id"), table_name="upgrade_applications")
    op.drop_table("upgrade_applications")
    op.drop_index(op.f("ix_kit_photos_kit_id"), table_name="kit_photos")
    op.drop_table("kit_photos")
    op.drop_index(op.f("ix_kits_status"), table_name="kits")
    op.drop_table("kits")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_index(op.f("ix_upgrades_name"), table_name="upgrades")
    op.drop_table("upgrades")
    op.drop_index(op.f("ix_tools_name"), table_name="tools")
    op.drop_table("tools")
    op.drop_index(op.f("ix_retailers_name"), table_name="retailers")
    op.drop_table("retailers")
    op.drop_index(op.f("ix_consumables_name"), table_name="consumables")
    op.drop_table("consumables")
    # ### end Alembic commands ###
